from settings import *

DEBUG = TEMPLATE_DEBUG = False

ALLOWED_HOSTS = ['154.117.8.18']

STATIC_URL = "/static/"

BILLING_URL = "http://154.117.8.18:8080/"

PACKAGES_URL = BILLING_URL + "packages/"

PACKAGE_INSERT_URL = PACKAGES_URL + "insert/"

PACKAGE_DELETE_URL = PACKAGES_URL + "delete/"

INSTANT_VOUCHER_INSERT_URL = PACKAGES_URL + "insert_vouchers/"
